language: php
script: "php compile.php example.php output.php"
php:
  - '5.6'
  - '7.1'
  - nightly
  
before_install:
- wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
- chmod +x php-coveralls.phar
- composer require php-coveralls/php-coveralls
 
script:
- phpunit --coverage-clover build/logs/clover.xml
- php compile.php example.php output.php
