language: php
script: "php compile.php example.php output.php"
php:
  - '5.6'
  - '7.1'
  - hhvm # on Trusty only
  - nightly
  
before_install:
- composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
- composer install --dev
 
script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
 
after_script:
- php vendor/bin/coveralls -v